language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install -r ./requirements/requirements-testing.txt
  - pip install pylint coveralls
  - pip install codecov selenium

script:
  - pylint ./algorithm/data_structures/undirected_graph.py
  - python ./tests/test_searching.py -v

after_success:
  - coveralls
