language: python

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

install:
  - pip install -r ./requirements/requirements-testing.txt
  - pip install pylint coveralls

script:
  - pylint ./data_structures/undirected_graph.py
  - python ./tests/test_searching.py

after_success:
  - pip install codecov
  - coveralls
