language: python

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

install:
  - pip install --upgrade pip
  - pip install -r ./requirements/requirements-testing.txt
  - pip install pylint coveralls
  - pip install codecov

script:
  - pylint ./algorithm/data_structures/undirected_graph.py
  - python ./tests/test_searching.py -v

after_success:
  - coveralls
